[package]
name = "hello_world"
version = "0.0.0"
edition = "2018"

[dependencies.plugin]
version = "*"
path = "../../plugin"

[lib]
crate-type = ["dylib"]

# links against C libraries
# [lib]
# crate-type = ["cdylib"]